#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint
echo "Running lint"
yarn lint

# solhint
echo "Running solhint"
yarn solhint

# unit test
echo "Running test"
yarn test

echo "Checking if ABI files have changed"
yarn abi
if git diff --name-only | grep -q -E '\.abi$'; then
    echo "ABI files have been updated. Please add these changes and commit again."
    echo "You can do this by running:"
    echo "git add . && git commit -m 'Your commit message'"
    exit 1
fi
